title: "Marcel R. G. Berger"
description: "Digitale Projekte, Inhalte & rechtliche Angaben"
remote_theme: pages-themes/slate@v0.2.0
color_scheme: dark
logo: ""  # optional: Pfad zu einem Logo
nav_sort: manual
